"""Policy learning contract for acquisition allocators."""
from typing import Protocol, Iterable, Any
import torch

class Learner(Protocol):
    def act(self, obs: torch.Tensor, deterministic: bool = False) -> torch.Tensor: ...
    def observe(self, transition: Any) -> None: ...
    def update(self) -> dict: ...
    def save(self, path) -> None: ...
    def load(self, path) -> None: ...
    def policy_parameters(self) -> Iterable[torch.nn.Parameter]: ...
    def gradient_signature(self, batch: dict) -> torch.Tensor: ...
